# Generated by Django 5.0.6 on 2026-09-29 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=20, verbose_name='ФН')),
                ('fd', models.CharField(max_length=20, verbose_name='ФД')),
                ('fp', models.CharField(max_length=20, verbose_name='ФП')),
                ('purchased_at', models.DateTimeField(verbose_name='Дата и время покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('on_review', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='on_review', max_length=20, verbose_name='Статус')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='unique_receipt_fn_fd_fp'),
        ),
    ]
